spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.59:3306/takeAway?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.59
    port: 6379
    password:

server:
  context-path: /sell

weChat:
#  wechat payment
#  appId: wxd898fcb01713c658
#  wechat payment
#  appsecret: 8b7480add5af214ee585e9eed6f9a73f
  appId: wx292fb7a3ffd17def
  appsecret: 8b7480add5af214ee585e9eed6f9a73f
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  keyPath: /Users/zhangbowen/Programming/Project/coding-117/doc/h5.p12
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  mchId: 1483469312
  notifyUrl: http://markzhang.natapp1.cc/sell/pay/notify

weChatUrl:
  serverUrl: http://markzhang.natapp1.cc
#  openAuthRedirectUrl is the redirect url after scanning the qr code
  openAuthRedirectUrl: http://markzhang.natapp1.cc/sell/vendor/login
  projectUrl: http://markzhang.natapp1.cc
  qrAuthorizationReturnUrl: /sell/vendor/login
