spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.59:3306/takeAway?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

weChat:
#  wechat payment
#  appId: wxd898fcb01713c658
#  wechat payment
#  appsecret: 8b7480add5af214ee585e9eed6f9a73f
  appId: wx292fb7a3ffd17def
  appsecret: 8b7480add5af214ee585e9eed6f9a73f
  keyPath: /Users/zhangbowen/Programming/Project/coding-117/doc/h5.p12
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  mchId: 1483469312
  notifyUrl: http://markzhang.natapp1.cc/sell/pay/notify